"""
DNS Optimization Module.
"""

import asyncio
import time
import subprocess
from pathlib import Path
from dataclasses import dataclass
from typing import List, Optional

import dns.resolver

from turbowifi.core.platform import is_root


@dataclass
class DNSProvider:
    name: str
    primary: str
    secondary: str
    latency_ms: Optional[float] = None


PROVIDERS = [
    DNSProvider("Google", "8.8.8.8", "8.8.4.4"),
    DNSProvider("Cloudflare", "1.1.1.1", "1.0.0.1"),
    DNSProvider("Quad9", "9.9.9.9", "149.112.112.112"),
    DNSProvider("AdGuard", "94.140.14.14", "94.140.15.15"),
    DNSProvider("OpenDNS", "208.67.222.222", "208.67.220.220"),
]


async def _test_dns_server(server_ip: str, domain: str = "google.com") -> Optional[float]:
    """Test resolution latency against a specific DNS server."""
    resolver = dns.resolver.Resolver(configure=False)
    resolver.nameservers = [server_ip]
    resolver.lifetime = 2.0

    # Run in thread to not block event loop
    def _resolve():
        start = time.perf_counter()
        try:
            resolver.resolve(domain, "A")
            return (time.perf_counter() - start) * 1000.0
        except Exception:
            return None

    return await asyncio.to_thread(_resolve)


async def benchmark_dns_providers() -> List[DNSProvider]:
    """Benchmark all known providers and return them sorted by latency."""
    results = []

    # We test both primary and secondary and take the average
    for provider in PROVIDERS:
        lat1 = await _test_dns_server(provider.primary)
        lat2 = await _test_dns_server(provider.secondary)

        lats = [lat for lat in (lat1, lat2) if lat is not None]
        avg_lat = sum(lats) / len(lats) if lats else None

        results.append(
            DNSProvider(
                name=provider.name,
                primary=provider.primary,
                secondary=provider.secondary,
                latency_ms=avg_lat,
            )
        )

    # Sort valid ones first, then by latency
    results.sort(key=lambda p: (p.latency_ms is None, p.latency_ms))
    return results


class SystemdResolvedManager:
    """Manages DNS for Ubuntu systems using systemd-resolved."""

    def apply(self, interface: str, primary: str, secondary: str) -> bool:
        try:
            # resolvectl dns eth0 8.8.8.8 8.8.4.4
            subprocess.run(
                ["resolvectl", "dns", interface, primary, secondary],
                check=True,
                capture_output=True,
            )
            # Disable DHCP DNS overrides on this interface so ours stick
            subprocess.run(
                ["resolvectl", "ignore-auto-dns", interface, "yes"], check=True, capture_output=True
            )
            return True
        except subprocess.CalledProcessError:
            return False


class ResolvConfManager:
    """Manages DNS for traditional systems using /etc/resolv.conf."""

    FILE_PATH = "/etc/resolv.conf"

    def apply(self, primary: str, secondary: str) -> bool:
        if not is_root():
            return False

        content = f"# Generated by TurboWiFi AI\nnameserver {primary}\nnameserver {secondary}\n"
        try:
            Path(self.FILE_PATH).write_text(content)
            return True
        except OSError:
            return False
